### ISSUE TITLE
KnownIssueHandler disables JUnit Assumptions 

### ISSUE THREAD

**Issue by mchoma** [xtf-cz/xtf#279]
When JUnit assumption is used test is not skipped rather AssumptionViolatedException is thrown and test fails. 

Couldnt KnownIssueHandler 
1) implement `if (throwable instanceof AssumptionViolatedException)`
2) instead of `throw throwable;` delegate to default implementaiton of `handleTestExecutionException`

[1] https://github.com/xtf-cz/xtf/blob/master/junit5/src/main/java/cz/xtf/junit5/extensions/KnownIssueHandler.java

**Comment by Crumby** [comment]
@mchoma Are you using JUnit5 [assumptions](https://junit.org/junit5/docs/5.1.0/api/org/junit/jupiter/api/Assumptions.html)? Because those throw TestAbortedExeption that is understood as skipped. `AssumptionViolatedException` is thrown by JUnit4 assumptions and this exception isn't by default understood by JUnit Platform. You can try to add JUnit Vintage dependency to your maven-surefire if you don't want migrate your assumptions to JUnit5.

**Comment by mchoma** [comment]
Thanks for explaining, we moved to junit5. Closing.
