### ISSUE TITLE
More intelligent waiters

### ISSUE THREAD

**Issue by mnovak1** [xtf-cz/xtf#340]
Add waiter ability to wait for more complex events than pod up and pod down + implementation for the more common use cases.

Add waiter ability to fail fast, once a certain erroneous state has been detected (idea: lambdas for detection of error states, so it's configurable).

**Comment by Crumby** [comment]
> Add waiter ability to wait for more complex events than pod up and pod down + implementation for the more common use cases.

Which complex events and common use cases do you have in mind particularly? 

> Add waiter ability to fail fast, once a certain erroneous state has been detected (idea: lambdas for detection of error states, so it's configurable).

This feature is already implemented by both [SimpleWaiter](https://github.com/xtf-cz/xtf/blob/master/core/src/main/java/cz/xtf/core/waiting/SimpleWaiter.java) and [SupplierWaiter](https://github.com/xtf-cz/xtf/blob/master/core/src/main/java/cz/xtf/core/waiting/SupplierWaiter.java). You can set it dynamically in the former. Later has to be created with the failure condition passed in constructor by design atm.

Check out [isDcReady()](https://github.com/xtf-cz/xtf/blob/master/core/src/main/java/cz/xtf/core/openshift/OpenShiftWaiters.java#L121) and [hasBuildCompleted()](https://github.com/xtf-cz/xtf/blob/master/core/src/main/java/cz/xtf/core/openshift/OpenShiftWaiters.java#L36) waiters as they both are complex and both contain fail fast ability. I'm open to implementing other if their use case will be general enough.

**Comment by LittleJohnII** [comment]
@istraka with the fail-fast waiter support merged, can this be marked as done?

**Comment by fabiobrz** [comment]
> @istraka with the fail-fast waiter support merged, can this be marked as done?

+1, can we close this as done? The PR for it mentions the related issue should be fixed, but unfortunately that was in [a comment](https://github.com/xtf-cz/xtf/pull/366#issuecomment-646713620) by the author, rather than in the PR description.

CC @mnovak1

**Comment by mnovak1** [comment]
Closing.
